const productsData = [
  {
    id: 1,
    name: 'Karataş Motor Yağı',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T4 Serisi için yüksek performanslı motor yağı.',
    origin: 'Yerli',
  },
  {
    id: 2,
    name: 'Foton Yağ Filtresi',
    brand: 'foton',
    subCategory: 'FT Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FT Serisi için orijinal yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 3,
    name: 'Mutlu 60Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-60ah.jpg',
    description: 'Binek araçlar için Mutlu 60Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 4,
    name: 'Iveco Fren Balatası',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Daily için ön fren balatası seti.',
    origin: 'İthal',
  },
  {
    id: 5,
    name: 'Karataş Hava Filtresi',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T5 Serisi için yüksek kaliteli hava filtresi.',
    origin: 'Yerli',
  },
  {
    id: 6,
    name: 'Foton Hidrolik Yağ',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FTX Serisi için hidrolik sistem yağı.',
    origin: 'İthal',
  },
  {
    id: 7,
    name: 'Mutlu 70Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-60ah.jpg',
    description: 'Ticari araçlar için Mutlu 70Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 8,
    name: 'Iveco Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Erobus için orijinal yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 9,
    name: 'Karataş Yakıt Filtresi',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T4 Serisi için yakıt filtresi.',
    origin: 'Yerli',
  },
  {
    id: 10,
    name: 'Foton Hava Filtresi',
    brand: 'foton',
    subCategory: 'Lovol',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton Lovol serisi için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 11,
    name: 'Mutlu 80Ah Akü',
    brand: 'mutlu',
    subCategory: 'Aksesuar',
    image: '/images/mutlu-60ah.jpg',
    description: 'Ağır vasıtalar için Mutlu 80Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 12,
    name: 'Iveco Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Ducato',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Ducato için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 13,
    name: 'Karataş Yağ Filtresi',
    brand: 'karatas',
    subCategory: 'Karataş Parts',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş yedek parça yağ filtresi.',
    origin: 'Yerli',
  },
  {
    id: 14,
    name: 'Foton Yağ Filtresi',
    brand: 'foton',
    subCategory: 'Foton Parts',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton yedek parça yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 15,
    name: 'Mutlu 90Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-60ah.jpg',
    description: 'Premium binek araçlar için Mutlu 90Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 16,
    name: 'Iveco Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için yedek parça yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 17,
    name: 'Karataş Hidrolik Yağ',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T5 Serisi için hidrolik sistem yağı.',
    origin: 'Yerli',
  },
  {
    id: 18,
    name: 'Foton Motor Yağı',
    brand: 'foton',
    subCategory: 'FT Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FT Serisi için motor yağı.',
    origin: 'İthal',
  },
  {
    id: 19,
    name: 'Mutlu 100Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-60ah.jpg',
    description: 'Ağır ticari araçlar için Mutlu 100Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 20,
    name: 'Iveco Motor Yağı',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Erobus için motor yağı.',
    origin: 'İthal',
  },
  {
    id: 21,
    name: 'Karataş Yağ Filtresi',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T4 Serisi için yedek parça yağ filtresi.',
    origin: 'Yerli',
  },
  {
    id: 22,
    name: 'Foton Hava Filtresi',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FTX Serisi için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 23,
    name: 'Mutlu 110Ah Akü',
    brand: 'mutlu',
    subCategory: 'Aksesuar',
    image: '/images/mutlu-60ah.jpg',
    description: 'Özel araçlar için Mutlu 110Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 24,
    name: 'Iveco Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Ducato',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Ducato için yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 25,
    name: 'Karataş Motor Yağı',
    brand: 'karatas',
    subCategory: 'Karataş Parts',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş yedek parça motor yağı.',
    origin: 'Yerli',
  },
  {
    id: 26,
    name: 'Foton Hidrolik Yağ',
    brand: 'foton',
    subCategory: 'Lovol',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton Lovol serisi için hidrolik yağ.',
    origin: 'İthal',
  },
  {
    id: 27,
    name: 'Mutlu 120Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-60ah.jpg',
    description: 'Lüks binek araçlar için Mutlu 120Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 28,
    name: 'Iveco Hidrolik Yağ',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için hidrolik sistem yağı.',
    origin: 'İthal',
  },
  {
    id: 29,
    name: 'Karataş Yağ Filtresi',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T5 Serisi için yedek parça yağ filtresi.',
    origin: 'Yerli',
  },
  {
    id: 30,
    name: 'Foton Motor Yağı',
    brand: 'foton',
    subCategory: 'Foton Parts',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton yedek parça motor yağı.',
    origin: 'İthal',
  },
  {
    id: 31,
    name: 'Mutlu 130Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-60ah.jpg',
    description: 'Ağır iş makineleri için Mutlu 130Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 32,
    name: 'Iveco Motor Yağı',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Erobus için yedek parça motor yağı.',
    origin: 'İthal',
  },
  {
    id: 33,
    name: 'Karataş Hava Filtresi',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T4 Serisi için yedek parça hava filtresi.',
    origin: 'Yerli',
  },
  {
    id: 34,
    name: 'Foton Yağ Filtresi',
    brand: 'foton',
    subCategory: 'FT Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FT Serisi için yedek parça yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 35,
    name: 'Mutlu 140Ah Akü',
    brand: 'mutlu',
    subCategory: 'Aksesuar',
    image: '/images/mutlu-60ah.jpg',
    description: 'Özel projeler için Mutlu 140Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 36,
    name: 'Iveco Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Ducato',
    image: '/images/iveco-ducato-filter.jpg',
    description: 'Iveco Ducato için yedek parça yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 37,
    name: 'Karataş Hidrolik Yağ',
    brand: 'karatas',
    subCategory: 'Karataş Parts',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş yedek parça hidrolik yağ.',
    origin: 'Yerli',
  },
  {
    id: 38,
    name: 'Foton Hava Filtresi',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FTX Serisi için yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 39,
    name: 'Mutlu 150Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-60ah.jpg',
    description: 'Premium araçlar için Mutlu 150Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 40,
    name: 'Iveco Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 41,
    name: 'Karataş Yağ Filtresi',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T4 Serisi için yedek parça yağ filtresi.',
    origin: 'Yerli',
  },
  {
    id: 42,
    name: 'Foton Motor Yağı',
    brand: 'foton',
    subCategory: 'FT Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FT Serisi için motor yağı.',
    origin: 'İthal',
  },
  {
    id: 43,
    name: 'Mutlu 160Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-60ah.jpg',
    description: 'Ağır ticari araçlar için Mutlu 160Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 44,
    name: 'Iveco Motor Yağı',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Erobus için motor yağı.',
    origin: 'İthal',
  },
  {
    id: 45,
    name: 'Karataş Hava Filtresi',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T5 Serisi için hava filtresi.',
    origin: 'Yerli',
  },
  {
    id: 46,
    name: 'Foton Hidrolik Yağ',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FTX Serisi için hidrolik yağ.',
    origin: 'İthal',
  },
  {
    id: 47,
    name: 'Mutlu 170Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-60ah.jpg',
    description: 'Premium araçlar için Mutlu 170Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 48,
    name: 'Iveco Hidrolik Yağ',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için hidrolik yağ.',
    origin: 'İthal',
  },
  {
    id: 49,
    name: 'Karataş Hava Filtresi',
    brand: 'karatas',
    subCategory: 'Karataş Parts',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş yedek parça hava filtresi.',
    origin: 'Yerli',
  },
  {
    id: 50,
    name: 'Foton Yağ Filtresi',
    brand: 'foton',
    subCategory: 'FT Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FT Serisi için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 51,
    name: 'Mutlu 180Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-60ah.jpg',
    description: 'Premium araçlar için Mutlu 180Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 52,
    name: 'Iveco Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için yedek parça yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 53,
    name: 'Karataş Hidrolik Yağ',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-oil.jpg',
    description: 'Karataş T5 Serisi için yedek parça hidrolik yağ.',
    origin: 'Yerli',
  },
  {
    id: 54,
    name: 'Foton Hava Filtresi',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-oil-filter.jpg',
    description: 'Foton FTX Serisi için yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 55,
    name: 'Mutlu 190Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-60ah.jpg',
    description: 'Ağır iş makineleri için Mutlu 190Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 56,
    name: 'Iveco Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Erobus için yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 57,
    name: 'CNH Industrial Disk Fren',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk.jpg',
    description: 'CNH Industrial için yüksek performanslı disk fren sistemi.',
    origin: 'İthal',
  },
  {
    id: 58,
    name: 'Valeo Fren Balata Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-brake-set.jpg',
    description: 'Valeo premium fren balata seti.',
    origin: 'İthal',
  },
  {
    id: 59,
    name: 'MGA Ön Fren Balatası',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-front-brake.jpg',
    description: 'MGA ön fren balatası seti.',
    origin: 'Yerli',
  },
  {
    id: 60,
    name: 'Dönmez Fren Balata Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-brake-set.jpg',
    description: 'Dönmez fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 61,
    name: 'GMW Arka Fren Balatası',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-rear-brake.jpg',
    description: 'GMW arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 62,
    name: 'AYD Ön Fren Balatası',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-front-brake.jpg',
    description: 'AYD ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 63,
    name: 'Krafvoll Fren Balata Seti',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-brake-set.jpg',
    description: 'Krafvoll fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 64,
    name: 'Braxis Arka Fren Balatası',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-rear-brake.jpg',
    description: 'Braxis arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 65,
    name: 'Eker Ön Fren Balatası',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-front-brake.jpg',
    description: 'Eker ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 66,
    name: 'Veka Fren Balata Seti',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-brake-set.jpg',
    description: 'Veka fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 67,
    name: 'Karataş T4 Motor Yağı',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-t4-oil.jpg',
    description: 'Karataş T4 Serisi için özel motor yağı.',
    origin: 'Yerli',
  },
  {
    id: 68,
    name: 'Foton FTX Hidrolik Yağ',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-ftx-hydraulic.jpg',
    description: 'Foton FTX Serisi için hidrolik sistem yağı.',
    origin: 'İthal',
  },
  {
    id: 69,
    name: 'Mutlu 200Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-200ah.jpg',
    description: 'Ağır iş makineleri için Mutlu 200Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 70,
    name: 'Iveco Daily Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 71,
    name: 'CNH Industrial Disk Set',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk-set.jpg',
    description: 'CNH Industrial disk fren seti.',
    origin: 'İthal',
  },
  {
    id: 72,
    name: 'Valeo Arka Fren Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-rear-set.jpg',
    description: 'Valeo arka fren balata seti.',
    origin: 'İthal',
  },
  {
    id: 73,
    name: 'MGA Arka Fren Balatası',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-rear-brake.jpg',
    description: 'MGA arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 74,
    name: 'Dönmez Ön Fren Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-front-set.jpg',
    description: 'Dönmez ön fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 75,
    name: 'GMW Fren Balata Seti',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-brake-set.jpg',
    description: 'GMW fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 76,
    name: 'AYD Arka Fren Balatası',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-rear-brake.jpg',
    description: 'AYD arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 77,
    name: 'Krafvoll Ön Fren Balatası',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-front-brake.jpg',
    description: 'Krafvoll ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 78,
    name: 'Braxis Fren Balata Seti',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-brake-set.jpg',
    description: 'Braxis fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 79,
    name: 'Eker Arka Fren Balatası',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-rear-brake.jpg',
    description: 'Eker arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 80,
    name: 'Veka Ön Fren Balatası',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-front-brake.jpg',
    description: 'Veka ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 81,
    name: 'Karataş T5 Hava Filtresi',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-t5-air.jpg',
    description: 'Karataş T5 Serisi için hava filtresi.',
    origin: 'Yerli',
  },
  {
    id: 82,
    name: 'Foton Lovol Yağ Filtresi',
    brand: 'foton',
    subCategory: 'Lovol',
    image: '/images/foton-lovol-filter.jpg',
    description: 'Foton Lovol serisi için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 83,
    name: 'Mutlu 210Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-210ah.jpg',
    description: 'Premium araçlar için Mutlu 210Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 84,
    name: 'Iveco Erobus Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-erobus-air.jpg',
    description: 'Iveco Erobus için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 85,
    name: 'CNH Industrial Disk Balata',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk-pad.jpg',
    description: 'CNH Industrial disk fren balatası.',
    origin: 'İthal',
  },
  {
    id: 86,
    name: 'Valeo Ön Fren Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-front-set.jpg',
    description: 'Valeo ön fren balata seti.',
    origin: 'İthal',
  },
  {
    id: 87,
    name: 'MGA Fren Balata Seti',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-brake-set.jpg',
    description: 'MGA fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 88,
    name: 'Dönmez Arka Fren Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-rear-set.jpg',
    description: 'Dönmez arka fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 89,
    name: 'GMW Ön Fren Balatası',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-front-brake.jpg',
    description: 'GMW ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 90,
    name: 'AYD Fren Balata Seti',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-brake-set.jpg',
    description: 'AYD fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 91,
    name: 'Krafvoll Arka Fren Balatası',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-rear-brake.jpg',
    description: 'Krafvoll arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 92,
    name: 'Braxis Ön Fren Balatası',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-front-brake.jpg',
    description: 'Braxis ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 93,
    name: 'Eker Fren Balata Seti',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-brake-set.jpg',
    description: 'Eker fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 94,
    name: 'Veka Arka Fren Balatası',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-rear-brake.jpg',
    description: 'Veka arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 95,
    name: 'Karataş Parts Yağ Filtresi',
    brand: 'karatas',
    subCategory: 'Karataş Parts',
    image: '/images/karatas-parts-filter.jpg',
    description: 'Karataş yedek parça yağ filtresi.',
    origin: 'Yerli',
  },
  {
    id: 96,
    name: 'Foton Parts Hava Filtresi',
    brand: 'foton',
    subCategory: 'Foton Parts',
    image: '/images/foton-parts-air.jpg',
    description: 'Foton yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 97,
    name: 'Mutlu 220Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-220ah.jpg',
    description: 'Ağır ticari araçlar için Mutlu 220Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 98,
    name: 'Iveco Ducato Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Ducato',
    image: '/images/iveco-ducato-filter.jpg',
    description: 'Iveco Ducato için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 99,
    name: 'CNH Industrial Disk Set',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk-set-2.jpg',
    description: 'CNH Industrial disk fren seti.',
    origin: 'İthal',
  },
  {
    id: 100,
    name: 'Valeo Fren Balata Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-brake-set-2.jpg',
    description: 'Valeo fren balata seti.',
    origin: 'İthal',
  },
  {
    id: 101,
    name: 'MGA Ön Fren Balatası',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-front-brake-2.jpg',
    description: 'MGA ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 102,
    name: 'Dönmez Fren Balata Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-brake-set-2.jpg',
    description: 'Dönmez fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 103,
    name: 'GMW Arka Fren Balatası',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-rear-brake-2.jpg',
    description: 'GMW arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 104,
    name: 'AYD Ön Fren Balatası',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-front-brake-2.jpg',
    description: 'AYD ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 105,
    name: 'Krafvoll Fren Balata Seti',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-brake-set-2.jpg',
    description: 'Krafvoll fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 106,
    name: 'Braxis Arka Fren Balatası',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-rear-brake-2.jpg',
    description: 'Braxis arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 107,
    name: 'Eker Ön Fren Balatası',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-front-brake-2.jpg',
    description: 'Eker ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 108,
    name: 'Veka Fren Balata Seti',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-brake-set-2.jpg',
    description: 'Veka fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 109,
    name: 'Karataş T4 Motor Yağı',
    brand: 'karatas',
    subCategory: 'T4 Serisi',
    image: '/images/karatas-t4-oil-2.jpg',
    description: 'Karataş T4 Serisi için motor yağı.',
    origin: 'Yerli',
  },
  {
    id: 110,
    name: 'Foton FTX Hidrolik Yağ',
    brand: 'foton',
    subCategory: 'FTX Serisi',
    image: '/images/foton-ftx-hydraulic-2.jpg',
    description: 'Foton FTX Serisi için hidrolik yağ.',
    origin: 'İthal',
  },
  {
    id: 111,
    name: 'Mutlu 230Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-230ah.jpg',
    description: 'Premium araçlar için Mutlu 230Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 112,
    name: 'Iveco Daily Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter-2.jpg',
    description: 'Iveco Daily için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 113,
    name: 'CNH Industrial Disk Fren',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk-2.jpg',
    description: 'CNH Industrial disk fren.',
    origin: 'İthal',
  },
  {
    id: 114,
    name: 'Valeo Arka Fren Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-rear-set-2.jpg',
    description: 'Valeo arka fren seti.',
    origin: 'İthal',
  },
  {
    id: 115,
    name: 'MGA Arka Fren Balatası',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-rear-brake-2.jpg',
    description: 'MGA arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 116,
    name: 'Dönmez Ön Fren Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-front-set-2.jpg',
    description: 'Dönmez ön fren seti.',
    origin: 'Yerli',
  },
  {
    id: 117,
    name: 'GMW Fren Balata Seti',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-brake-set-2.jpg',
    description: 'GMW fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 118,
    name: 'AYD Arka Fren Balatası',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-rear-brake-2.jpg',
    description: 'AYD arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 119,
    name: 'Krafvoll Ön Fren Balatası',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-front-brake-2.jpg',
    description: 'Krafvoll ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 120,
    name: 'Braxis Fren Balata Seti',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-brake-set-2.jpg',
    description: 'Braxis fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 121,
    name: 'Eker Arka Fren Balatası',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-rear-brake-2.jpg',
    description: 'Eker arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 122,
    name: 'Veka Ön Fren Balatası',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-front-brake-2.jpg',
    description: 'Veka ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 123,
    name: 'Karataş T5 Hava Filtresi',
    brand: 'karatas',
    subCategory: 'T5 Serisi',
    image: '/images/karatas-t5-air-2.jpg',
    description: 'Karataş T5 Serisi için hava filtresi.',
    origin: 'Yerli',
  },
  {
    id: 124,
    name: 'Foton Lovol Yağ Filtresi',
    brand: 'foton',
    subCategory: 'Lovol',
    image: '/images/foton-lovol-filter-2.jpg',
    description: 'Foton Lovol serisi için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 125,
    name: 'Mutlu 240Ah Akü',
    brand: 'mutlu',
    subCategory: 'Ticari',
    image: '/images/mutlu-240ah.jpg',
    description: 'Ağır ticari araçlar için Mutlu 240Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 126,
    name: 'Iveco Erobus Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-erobus-air-2.jpg',
    description: 'Iveco Erobus için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 127,
    name: 'CNH Industrial Disk Balata',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk-pad-2.jpg',
    description: 'CNH Industrial disk balata.',
    origin: 'İthal',
  },
  {
    id: 128,
    name: 'Valeo Ön Fren Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-front-set-2.jpg',
    description: 'Valeo ön fren seti.',
    origin: 'İthal',
  },
  {
    id: 129,
    name: 'MGA Fren Balata Seti',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-brake-set-3.jpg',
    description: 'MGA fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 130,
    name: 'Dönmez Arka Fren Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-rear-set-2.jpg',
    description: 'Dönmez arka fren seti.',
    origin: 'Yerli',
  },
  {
    id: 131,
    name: 'GMW Ön Fren Balatası',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-front-brake-3.jpg',
    description: 'GMW ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 132,
    name: 'AYD Fren Balata Seti',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-brake-set-3.jpg',
    description: 'AYD fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 133,
    name: 'Krafvoll Arka Fren Balatası',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-rear-brake-3.jpg',
    description: 'Krafvoll arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 134,
    name: 'Braxis Ön Fren Balatası',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-front-brake-3.jpg',
    description: 'Braxis ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 135,
    name: 'Eker Fren Balata Seti',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-brake-set-3.jpg',
    description: 'Eker fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 136,
    name: 'Veka Arka Fren Balatası',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-rear-brake-3.jpg',
    description: 'Veka arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 137,
    name: 'Karataş Parts Yağ Filtresi',
    brand: 'karatas',
    subCategory: 'Karataş Parts',
    image: '/images/karatas-parts-filter-2.jpg',
    description: 'Karataş yedek parça yağ filtresi.',
    origin: 'Yerli',
  },
  {
    id: 138,
    name: 'Foton Parts Hava Filtresi',
    brand: 'foton',
    subCategory: 'Foton Parts',
    image: '/images/foton-parts-air-2.jpg',
    description: 'Foton yedek parça hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 139,
    name: 'Mutlu 250Ah Akü',
    brand: 'mutlu',
    subCategory: 'Binek',
    image: '/images/mutlu-250ah.jpg',
    description: 'Premium araçlar için Mutlu 250Ah akü.',
    origin: 'Yerli',
  },
  {
    id: 140,
    name: 'Iveco Ducato Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Ducato',
    image: '/images/iveco-ducato-filter-2.jpg',
    description: 'Iveco Ducato için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 141,
    name: 'CNH Industrial Disk Set',
    brand: 'cnh industrial',
    subCategory: 'Disk',
    image: '/images/cnh-disk-set-3.jpg',
    description: 'CNH Industrial disk set.',
    origin: 'İthal',
  },
  {
    id: 142,
    name: 'Valeo Fren Balata Seti',
    brand: 'valeo',
    subCategory: 'Set',
    image: '/images/valeo-brake-set-3.jpg',
    description: 'Valeo fren balata seti.',
    origin: 'İthal',
  },
  {
    id: 143,
    name: 'MGA Ön Fren Balatası',
    brand: 'mga',
    subCategory: 'Balata',
    image: '/images/mga-front-brake-3.jpg',
    description: 'MGA ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 144,
    name: 'Dönmez Fren Balata Seti',
    brand: 'dönmez',
    subCategory: 'Set',
    image: '/images/donmez-brake-set-3.jpg',
    description: 'Dönmez fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 145,
    name: 'GMW Arka Fren Balatası',
    brand: 'gmw',
    subCategory: 'Balata',
    image: '/images/gmw-rear-brake-3.jpg',
    description: 'GMW arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 146,
    name: 'AYD Ön Fren Balatası',
    brand: 'ayd',
    subCategory: 'Balata',
    image: '/images/ayd-front-brake-3.jpg',
    description: 'AYD ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 147,
    name: 'Krafvoll Fren Balata Seti',
    brand: 'krafvoll',
    subCategory: 'Balata',
    image: '/images/krafvoll-brake-set-3.jpg',
    description: 'Krafvoll fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 148,
    name: 'Braxis Arka Fren Balatası',
    brand: 'braxis',
    subCategory: 'Balata',
    image: '/images/braxis-rear-brake-3.jpg',
    description: 'Braxis arka fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 149,
    name: 'Eker Ön Fren Balatası',
    brand: 'eker',
    subCategory: 'Balata',
    image: '/images/eker-front-brake-3.jpg',
    description: 'Eker ön fren balatası.',
    origin: 'Yerli',
  },
  {
    id: 150,
    name: 'Veka Fren Balata Seti',
    brand: 'veka',
    subCategory: 'Balata',
    image: '/images/veka-brake-set-3.jpg',
    description: 'Veka fren balata seti.',
    origin: 'Yerli',
  },
  {
    id: 151,
    name: 'Iveco Daily Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Daily',
    image: '/images/iveco-daily-filter.jpg',
    description: 'Iveco Daily için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 152,
    name: 'Iveco Eurokargo Fren Balatası',
    brand: 'iveco',
    subCategory: 'Eurokargo',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco Eurokargo için ön fren balatası seti.',
    origin: 'İthal',
  },
  {
    id: 153,
    name: 'Iveco Erobus Hava Filtresi',
    brand: 'iveco',
    subCategory: 'Erobus',
    image: '/images/iveco-erobus-air.jpg',
    description: 'Iveco Erobus için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 154,
    name: 'Iveco Ducato Yağ Filtresi',
    brand: 'iveco',
    subCategory: 'Ducato',
    image: '/images/iveco-ducato-filter.jpg',
    description: 'Iveco Ducato için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 155,
    name: 'Iveco 120-14 Yağ Filtresi',
    brand: 'iveco',
    subCategory: '120-14',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco 120-14 modelleri için yağ filtresi.',
    origin: 'İthal',
  },
  {
    id: 156,
    name: 'Iveco 85-12 Fren Balatası',
    brand: 'iveco',
    subCategory: '85-12',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco 85-12 için ön fren balatası seti.',
    origin: 'İthal',
  },
  {
    id: 157,
    name: 'Iveco 65-9 Hava Filtresi',
    brand: 'iveco',
    subCategory: '65-9',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco 65-9 için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 158,
    name: 'Iveco 65-12 Hava Filtresi',
    brand: 'iveco',
    subCategory: '65-12',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco 65-12 için hava filtresi.',
    origin: 'İthal',
  },
  {
    id: 159,
    name: 'Iveco 50NC Debriyaj Seti',
    brand: 'iveco',
    subCategory: '50NC',
    image: '/images/iveco-brake-pad.jpg',
    description: 'Iveco 50NC için debriyaj seti.',
    origin: 'İthal',
  }
];

export default productsData; 